### PR TITLE
Add dashboard uids for Grafana 8 side navigation

### LINKED ISSUE #48: 404 - Plugin not functioning
# Opening a Dashboard
`https://grafana.example.dev/api/plugin-proxy/cloudflare-app/with-key/api/v4/zones?status=active&per_page=50`

Has 404 not found:

```
{"message":"Not found"}
```

image

# Updating Config

https://grafana.example.dev/admin/plugins/cloudflare-app?page=config

`404 Not Found`

### PR DESCRIPTION
**Pull request by ghost**
Fixes: #48
References: https://grafana.com/docs/grafana/latest/developers/plugins/migration-guide/#update-needed-for-app-plugins-using-dashboards

### CODE REVIEW

**Review by Fattouche — APPROVED** [review]

**Comment by janik-cloudflare** [comment]
`defaultNav` doesn't seem to be working yet for some reason. :eyes:

**Comment by tolzhabayev** [comment]
@janik-cloudflare we are looking internally on why the defaultNav is not working in your case. I will get back to you asap.

**Comment by tolzhabayev** [comment]
@janik-cloudflare it is indeed a [bug](https://github.com/grafana/grafana/issues/46412) and will be fixed in the next release. 

A possible workaround for now is: https://github.com/grafana/grafana/issues/46412#issuecomment-1064234340

**Comment by janik-cloudflare** [comment]
Thanks for the quick update @tolzhabayev! I think we'll use your work-around for now and then re-enable `defaultNav` it in the next release of this plugin.

**Pull request merged**
